remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: The Seven Stand, Eight Fall Page
description: my next tattoo

